# Generated by Django 4.2.6 on 2023-10-18 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('description', models.BigIntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('graduation_year', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gov_id_type', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('id_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('no_of_sessions', models.IntegerField()),
                ('occurence', models.IntegerField()),
                ('relevant_topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.category')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.category')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('experience', models.IntegerField(default=0)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('other_links', models.CharField(blank=True, max_length=255, null=True)),
                ('mentoring_exp', models.IntegerField(default=0)),
                ('mentoring_type', models.CharField(blank=True, max_length=255, null=True)),
                ('availability', models.CharField(blank=True, max_length=255, null=True)),
                ('prefered_starttime', models.TimeField(blank=True, null=True)),
                ('prefered_endtime', models.TimeField(blank=True, null=True)),
                ('prefered_days', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mentoring.certification')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mentoring.company')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mentoring.education')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mentoring.identity')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mentoring.industry')),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mentoring.resource')),
                ('sessions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mentoring.session')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mentoring.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expertise', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('goals', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mentoring.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
