# Generated by Django 4.2 on 2023-10-20 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('issuer', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('graduation_year', models.IntegerField(null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('workplace', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gov_id_type', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('id_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expertise', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('goals', models.CharField(max_length=255)),
                ('links', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_mentor_country', models.CharField(max_length=255)),
                ('tools', models.CharField(blank=True, max_length=255, null=True)),
                ('discipline', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mentoring.company')),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('yearsofExp', models.IntegerField(default=0)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('other_links', models.CharField(blank=True, max_length=255, null=True)),
                ('mentoring_exp', models.IntegerField(default=0)),
                ('mentoring_type', models.CharField(blank=True, max_length=255, null=True)),
                ('availability', models.CharField(blank=True, max_length=255, null=True)),
                ('prefered_time', models.CharField(blank=True, max_length=225, null=True)),
                ('prefered_days', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('certification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.certification')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.company')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.education')),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.identity')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.industry')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('no_of_sessions', models.IntegerField(null=True)),
                ('occurence', models.IntegerField(null=True)),
                ('mentee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentoring.mentee')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentoring.mentor')),
                ('relevant_topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.category')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.resource'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.skill'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentee',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.skill'),
        ),
        migrations.AddField(
            model_name='mentee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
