# Generated by Django 4.2.6 on 2023-10-21 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='no_of_sessions',
            new_name='attendees_limit',
        ),
        migrations.RemoveField(
            model_name='session',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='session',
            name='type',
        ),
        migrations.AddField(
            model_name='session',
            name='no_of_session',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_state',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='type_of_session',
            field=models.CharField(choices=[('f', 'f'), ('o', 'o'), ('r', 'r')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='relevant_topics',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('available_time_slot', models.TimeField()),
                ('time_zone', models.CharField(max_length=100)),
                ('subscription_plans', models.CharField(max_length=100)),
                ('pricing', models.FloatField()),
                ('notes', models.CharField(max_length=255)),
                ('mentee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentoring.mentee')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.session')),
            ],
        ),
    ]
