# Generated by Django 4.2 on 2023-10-19 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certification',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='id_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='no_of_sessions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='occurence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
