# Generated by Django 4.2.6 on 2023-10-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_alter_session_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='CourseContents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentoring.coursecontent'),
        ),
    ]
