# Generated by Django 4.2 on 2023-10-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_alter_certification_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='sessions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.session'),
        ),
    ]
