# Generated by Django 4.2.6 on 2023-10-22 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentoring', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
