# Generated by Django 4.2.6 on 2023-10-20 02:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('workplace', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='mentee',
            name='links',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.experience'),
        ),
    ]
