# Generated by Django 4.2.6 on 2023-10-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0003_experience_mentee_links_mentee_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='experience',
            new_name='yearsofExp',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='prefered_endtime',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='prefered_starttime',
        ),
        migrations.AddField(
            model_name='mentor',
            name='prefered_time',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
