# Generated by Django 4.2 on 2023-10-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0003_alter_mentor_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='resources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.resource'),
        ),
    ]
