# Generated by Django 4.2 on 2023-10-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0005_alter_mentor_identity_alter_mentor_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
