# Generated by Django 4.2 on 2023-10-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0008_alter_mentor_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.company'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.education'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mentoring.skill'),
        ),
    ]
